"""add ats scoring columns

Revision ID: 781f7635d6a3
Revises: 38a1554e4dc5
Create Date: 2026-07-10 01:05:38.071399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781f7635d6a3'
down_revision: Union[str, Sequence[str], None] = '38a1554e4dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_results', sa.Column('ats_score', sa.String(), nullable=True))
    op.add_column('match_results', sa.Column('ats_found_keywords', sa.Text(), nullable=True))
    op.add_column('match_results', sa.Column('ats_missing_keywords', sa.Text(), nullable=True))
    op.add_column('match_results', sa.Column('ats_format_score', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_results', 'ats_format_score')
    op.drop_column('match_results', 'ats_missing_keywords')
    op.drop_column('match_results', 'ats_found_keywords')
    op.drop_column('match_results', 'ats_score')
    # ### end Alembic commands ###
