"""initial schema

Revision ID: fbfb4ab1cf61
Revises: 
Create Date: 2026-07-09 17:30:51.148191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbfb4ab1cf61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_years_experience', sa.String(), nullable=True),
    sa.Column('salary_min', sa.String(), nullable=True),
    sa.Column('salary_max', sa.String(), nullable=True),
    sa.Column('remote', sa.String(), nullable=True),
    sa.Column('apply_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('match_results',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('resume_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('vector_similarity', sa.String(), nullable=False),
    sa.Column('skill_overlap_ratio', sa.String(), nullable=False),
    sa.Column('blended_score', sa.String(), nullable=False),
    sa.Column('matched_skills', sa.Text(), nullable=False),
    sa.Column('missing_skills', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_match_results_job_id'), 'match_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_match_results_resume_id'), 'match_results', ['resume_id'], unique=False)
    op.create_table('resumes',
    sa.Column('resume_id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_data', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.String(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.create_index(op.f('ix_resumes_file_hash'), 'resumes', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_file_hash'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_match_results_resume_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_job_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_table('jobs')
    # ### end Alembic commands ###
